server:
  port: 8989
  servlet:
    context-path: /store

spring:
  datasource:
    url: jdbc:h2:file:C:\java\Architecture\architecture-project\db\demo;MV_STORE=false
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
#                  auto: create
          auto: update

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html